# Site settings
title: Salma Elshahawy
description: 'Business-minded data scientist with demonstrated skills to infer worthy insights through data analytics'
url: 'https://salma71.github.io'
keywords: "software, engineer, data, scientist, blog, CUNY, data science, data analyst, machine learning"
baseurl: ''
image: '/images/salma.jpg'
profilepic: '/images/salma.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
# font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Salma Elshahawy'
  email: salmaeng71@gmail.com
  twitter_username: salmaeng
  github_username:  salma71
  linkedin_username: salma-elshahawy/
  medium_username: salmaeng71
  stackoverflow_name: 8111013/salma/
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
paginate: 3
paginate_path: "/page:num/"
exclude: ['README.md', 'screenshot-overview.png']
